mode: debug
mysql:
  dsn: >-
    root:root@tcp(127.0.0.1:3306)/lime?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
redis:
  host: 127.0.0.1:6379
  auth:
  pool:
    min: 3
    max: 20
mongo:
  host: ${LIME_MONGO_HOST}
  port: ${LIME_MONGO_PORT}
  db: ${LIME_MONGO_DB}
  username: ${LIME_MONGO_USERNAME}
  password: ${LIME_MONGO_PASSWORD}
  authSource: ${LIME_MONGO_AUTHSOURCE}
cors:
  allow_credentials: false
  allow_headers:
    - '*'
  allow_methods:
    - GET
    - POST
    - OPTIONS
    - PUT
    - DELETE
  allow_origins:
    - '*'
  enable: false
  max_age: 7200
upload:
  image_prefix_url: "http://127.0.0.1:8000"
  image_save_path: "data/images/"
  image_max_size: 5
  image_allow_exts:
    - .jpg
    - .jpeg
    - .png"